settings:
  general:
    first-time-use: true
    currency_name: "coins"

trading:
  allow-cross-world: true
  blacklist-items:
    - "minecraft:bedrock"
    - "minecraft:command_block"

shops:
  shop-creation-cost: 100

economy:
  default-balance: 250

player-data:
  players-joined: []