settings:
  general:
    first-load: true
    currency_name: "coins"
    verbose: false

trading:
  allow-cross-world: true
  blacklist-items:
    - "minecraft:bedrock"
    - "minecraft:command_block"

shops:
  shop-creation-cost: 100

player-data:
  players-joined: []